name: imc_fitscore
description: Aplicativo de cálculo do Índice de Massa Corporal
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/barlow/Barlow-Regular.ttf
        - asset: assets/fonts/barlow/Barlow-Italic.ttf
          style: italic
        - asset: assets/fonts/barlow/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/barlow/Barlow-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/barlow/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/barlow/Barlow-BoldItalic.ttf
          style: italic
          weight: 700

flutter_gen:
  output: lib/gen/

  colors:
    inputs:
      - assets/colors/colors.xml